version: '3'

services:
    apache:
        build: .docker/apache
        container_name: budgets_apache
        ports:
          - 8080:80
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - .:/home/wwwroot/budgets
        depends_on:
          - php

    mysql:
        image: mysql:5.7
        container_name: budgets_mysql
        volumes:
            - .docker/data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: budgets
            MYSQL_USER: budgets
            MYSQL_PASSWORD: budgets
        ports:
            - 3305:3306

    php:
        build: .docker/php
        working_dir: /home/wwwroot/budgets
        container_name: budgets_php
        volumes:
          - .:/home/wwwroot/budgets
        environment:
          - maildev_host=budgets_maildev
        depends_on:
          - mysql
